### ISSUE TITLE
Definitives Löschen geht nur, wenn Kontakte eine Rolle haben.

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#1]
Kontakten unter "Gelöschte Personen" muss zuerst eine Rolle zugewiesen werden, bevor sie gelöscht werden können. Das ist etwas unlogisch. Mein Wunsch wäre, dass nur Personen ganz ohne Rolle gelöscht werden können.
Korrekte Lösung wäre deshalb wohl, dass Admin in dieser pseudo Gruppe Lese-Rechte an den Personen-Details hätten und nur da auf der einzelnen Person der Lösch-Knopf angezeigt würde. (Wichtig ist, dass der Admin vor dem Löschen den Verlauf kontrollieren kann. Bei Dubletten ist es wichtig, dass da keine Verknüpfungen mehr bestehen.)

**Comment by maede97** [comment]
Eine Person ohne Rollen kann via Suche gefunden werden und dann gelöscht werden.
Dies reicht für uns.
