### ISSUE TITLE
Weiterentwicklung Kurse und Anmeldungen

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#101]
Verschiedene Kurs anliegen sollten diskutiert werden:
- Cevianer sollten sich selbst als Leiter anmelden können. (vgl. auch https://github.com/hitobito/hitobito_cevi/issues/8)
- Kurs-Marktplatz aktivieren
- provisorische Anmeldungen testen

**Comment by nchiapol** [comment]
* Habe eben versucht die provisorische Anmeldung zu testesn aber nicht herausgefunden, wie die Funktioniert ;-)
  * Kurs-Marktplatz müssten wir wohl ebenfalls mal zuerst besprechen, bevor wir das in einen Sprint aufnehmen können. 

Die Anderen Anliegen sind für den Sprint markiert.

**Comment by maede97** [comment]
Weiter könnte auch die Anmeldung verbessert werden, siehe https://github.com/cevi/hitobito_cevi/issues/116

**Comment by maede97** [comment]
https://github.com/cevi/hitobito_cevi/issues/129

**Comment by tschuepbach** [comment]
**SLRG**
Folgende Anpassungen zur Überlegung
- [ ] Hinterlegung SLRG-Nummer (analog J+S-Nummer); Vereinfachung für Kursadmin, kann momentan via Anmeldeangaben gelöst werden
- [ ] TN-Liste Export gemäss Import-Vorlage der SLRG (low prio); Vereinfachung für Kursadmin; wird für den Import auf der SLRG-Datenbank benötigt

**Comment by nchiapol** [comment]
Issues:
* https://github.com/hitobito/hitobito_cevi/issues/79
* https://github.com/hitobito/hitobito_cevi/issues/80
* https://github.com/hitobito/hitobito_cevi/issues/81
* https://github.com/hitobito/hitobito_cevi/issues/81
* https://github.com/hitobito/hitobito_cevi/issues/82
* https://github.com/hitobito/hitobito_cevi/issues/84
* https://github.com/hitobito/hitobito_cevi/issues/85

**Comment by tschuepbach** [comment]
Mit der Einführung der neuen NDS (geplant für Dezember 2022) gelten neue Anforderungen für die Exporte resp. CSV-Importe.
Hier sind die entsprechenden Anleitungen zu finden: https://www.jugendundsport.ch/de/themen/neue-nds/anleitungen.html

Ich platziere dies hier mal als Erinnerung. Je nach Workflow auf der neuen Datenbank wird dies zu Anpassungen bei unseren Exporten führen.

**Comment by tschuepbach** [comment]
Idee (low prio)

Neu läuft die Anmeldung der J+S-MFE (Modul Fortbildung Expert/in) über die DB, via "MIO" Externe Kurse. Dabei brauchen die TN eine Bestätigung der*des LKBs. Eine automatisierte LKB-Freigabe (analog Coach) wäre praktisch. Hierzu könnte wohl etwas vom core/PBS übernommen werden. 

vgl. PBS:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/40494600/164627358-9206ecd6-d052-45f8-a2b2-eaaa954358a4.png">

**Comment by tschuepbach** [comment]
**Neue Funktion Drittperson in NDS**

_Beschreibung folgt..._

**Comment by tschuepbach** [comment]
**Sichtbarkeit der J+S- & AHV-Nummer**

Bei -> Kursen -> Tab "Anmeldungen" -> Person auswählen wird die J+S- & AHV-Nummer nicht angezeigt, egal mit welchen Rechten. Dies wäre aber praktisch, um die Zulassungsbedingungen vor einer Zuteilung zu überprüfen.

Beispiel: ([LINK](https://cevi.puzzle.ch/groups/6/events/1160/participations/127763))
![Unbenannt](https://user-images.githubusercontent.com/40494600/170099638-07c0a4a0-666a-4753-896e-76742507cd8f.PNG)

Aktueller workflow:
Person zuteilen -> Tab "Teilnehmende" -> Spaltenauswahl oder Person in NDS per Name suchen.

**Comment by tschuepbach** [comment]
**Standardbeschreibung/Aufnahmebedingungen bei Kursen** (medium prio)

Unter Einstellungen -> Kursarten können sowohl die Standardbeschreibung sowie die Aufnahmebedingungen pro Kursart hinterleget werden:
![1](https://user-images.githubusercontent.com/40494600/176395472-3aa21c3c-5866-4c0a-a590-e403641beea2.jpg)

Bei den Kurs-Einstellungen werden diese automatisch übernommen.

Vgl. Standardbeschreibung (Hinterlegte Beschreibung per default, editierbar, Hinterlegte Beschreibung kann jederzeit "eingesetzt" werden):
![2](https://user-images.githubusercontent.com/40494600/176395594-98c35f8a-07d8-4d51-b209-87919929fc8e.jpg)

Bei den Aufnahmebedingungen ist das Feld leer, die hinterlegten Bedingen können nicht "eingesetzt" werden. Wird das Feld leer gelassen und der Kurs gespeichert, erscheint auf der Event-Übersicht trotzdem die hinterlegten Aufnahmebedingungen. Werden via Kurs Bedingungen definiert, werden diese bei den vordefinierten Bedingungen, hinten angehängt. Die vordefinierten Bedingungen können im Kurs selbst nicht bearbeitet werden.
![3](https://user-images.githubusercontent.com/40494600/176395612-9c1df2bb-f9cf-49e6-ad3a-27e23abb6ead.jpg)

![4](https://user-images.githubusercontent.com/40494600/176395620-80f0f0e0-7146-4f25-ae53-80f4849df74e.jpg)


Beispiel aus der Test-Umgebung: [https://cevi.puzzle.ch/groups/6/events/1161](url)

**Soll**
- Gleiches Verhalten für Aufnahmebedingungen wie bei den Standardbeschreibung

**Hintergrund**
Die J+S-Kursanmeldung/ -administration ab Stufe Expert*in läuft neu über die CeviDB. Das Arbeiten mit vordefinierten, hinterlegten und standardisierten Standardbeschreibung/Aufnahmebedingungen via Kursarten wär sehr praktisch und zeitsparend.

**Comment by nchiapol** [comment]
Sorry für die Lange Rekationszeit. Du hast recht, das Verhalten hier ist nicht besonders intuitiv... zu den einzelnen Punkten:
  * Beschreibung und Standardbeschreibung: Ich denke das verhalten auf der Kurs-Page ist sinnvoll. Dass die Standardbeschreibung im PDF auftaucht ist in meinen Augen ein Bug. (https://github.com/hitobito/hitobito_cevi/issues/88)
  * Aufnahmebedingungen: Hier scheint mir das aktuelle Verhalten richtig. Wenn ein Kurstyp gewisse Anforderungen hat, sollten die bei einem einzelnen Kurs nur ergänzt und nicht reduziert werden können. (Insbesondere, wenn in Zukunft das auch durch die Hauptleiter bearbeitet werden kann ;-)
  * Kurzname: Der Scheint in der Produktivumgebung ziemlich aktiv genutzt. Welche Nachteile siehst du?
  * J+S Bezeichnung: Das ist wohl für Fälle wie mein J+S Lagerleiter gedacht, der hiess in meiner Region damals Übergangsjahreskurs (ÜGJK). Da wir uns aber entschieden haben einfach nur J+S-Typen und nicht die regionsspezifischen Versionen davon abzubilden, brauchen wir das wohl nicht wirklich.

**Comment by nchiapol** [comment]
zum SLRG Export/Import vgl https://github.com/hitobito/hitobito/issues/1875

**Comment by tschuepbach** [comment]
> zum SLRG Export/Import vgl [hitobito/hitobito#1875](https://github.com/hitobito/hitobito/issues/1875)

Ich teile deine Einschätzung. Die Import-Funktion resp. Kurs-Administration von der SLRG ist eh eine Krücke, was ein reibungsloses Arbeiten per se schwierig gestaltet..

**Comment by nchiapol** [comment]
Das meiste ist mit unserem 2022 Sprint umgesetzt. Die weiteren Ideen/Wünsche führen wir als separate Issues.
