### ISSUE TITLE
Darstellungs-Fehler bei kleiner Auflösung

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#102]
Falls die Auflösung klein ist tritt auf einem Event ein Darstellungsfehler auf:
![Falsches_Layout](https://user-images.githubusercontent.com/14098502/80069872-5b0aed80-8542-11ea-83fa-bcfde7aa9e57.PNG)
Wenn das Fenster noch kleiner ist, ist das Problem weg, weil das ganze Menu nach oben wandert in die Mobile Ansicht.
![richtiges_layout](https://user-images.githubusercontent.com/14098502/80069924-72e27180-8542-11ea-8427-bd0e28091116.png)

Könnte mit #71 zusammen in einem Sprint gelöst werden.

**Comment by btemperli** [comment]
Ähnliches Problem mit dem Button "+ Rolle hinzufügen". Dieser bricht nicht korrekt um und verschwindet dann rechts hinter der Scrollleiste.

<img width="1014" alt="Bildschirmfoto 2021-02-25 um 22 12 26" src="https://user-images.githubusercontent.com/3005632/109217784-8f7cb500-77b6-11eb-9865-4523e4246443.png">

**Comment by nchiapol** [comment]
neu eröffnen, falls bei Bootstrap 5 immer noch vorhanden
