### ISSUE TITLE
Abo-Export zeigt nicht alle Personen

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#104]
### Test-Instanz
https://cevi.puzzle.ch/groups/5/mailing_lists/41 mit den folgenden Einstellungen:
![image](https://user-images.githubusercontent.com/14098502/88922975-404ac200-d271-11ea-8191-ee2b6e8953f6.png)

https://cevi.puzzle.ch/groups/5/people?filter_id=17 mit folgenden Einstellungen:
![image](https://user-images.githubusercontent.com/14098502/88922909-20b39980-d271-11ea-8c7e-f3f0e0b66878.png)

Der Abo-Export (z.B. Etiketten, C5) hat 444 Seiten, also **444** Personen.
Die Liste hat "139 Personen angezeigt. 308 weitere Personen sind für dich nicht sichtbar." Also total **447** Personen.

Wo sind die restlichen 3?

### Der Fehler tritt auch auf dem Produktiv-System auf.
Personneliste mit folgenden Rollen:
![image](https://user-images.githubusercontent.com/14098502/88923652-573de400-d272-11ea-945a-4f7a5144b310.png)
resultiert in folgenden Personen:
 ![image](https://user-images.githubusercontent.com/14098502/88923410-fa422e00-d271-11ea-9890-4ac310196881.png)
Die 3 Personen, mit "Ap" am Anfang sind in einer Familie und wohnen zusammen.
Auf dem Abo sind folgende Rollen:
![image](https://user-images.githubusercontent.com/14098502/88923561-35446180-d272-11ea-9de7-3e4f34a7dc65.png)
Im Export des Abo sind nur **80** Personen drin.
Und die Famile "Ap*" hat nur die eine Person "J" drin: (Haushalte zusammengefasst, andere Haushalte haben geklappt)
![image](https://user-images.githubusercontent.com/14098502/88924023-eba84680-d272-11ea-95f5-02f53ee40a98.png)

### TLDR:

- Abo hat nicht alle Personen drin.
- Auf die schnelle gibt es für mich keine Logik, wieso die Personen nicht drin sind (sind in verschiedenen Gruppen)

**Comment by nchiapol** [comment]
Habe das eben in der Integration nachzustellen versucht (und mir dafür die Rolle "Geschäftsstelle / Admin Ortsgruppen" gegeben). 

Das Problem scheint dort nur durch inkonsistent Auswahl von "Haushalte zusammenfassen" verursacht. Wenn ich das sowohl beim Abo wie auch bei der Personen-Liste deaktiviere habe ich beide male 447 Seiten bei den Couverts.

Auch die CSV sind in beiden Fällen gleich gross.

(die unterschiede in den PDFs sind in [additional.txt](https://github.com/cevi/hitobito_cevi/files/5005391/additional.txt))

**Comment by maede97** [comment]
Also du meinst einfach beim Export das Häckchen? Bei mir klappt das nicht. Die genannte Familie "Ap" ist nur einmal vertreten, nicht 3x.

**Comment by maede97** [comment]
Also auf der Integrations-Umgebung gehts, auf der Produktiv-Umgebung nicht!

**Comment by maede97** [comment]
Bin gerade noch ein bisschen am testen:
Die fehlenden Personen auf der Produktiv-Umgebung sind:

- alles LeiterInnen
- entweder Einzelkinder oder 3, wobei dann 2 fehlen.
- alles Gruppenleiter
--> was mir gerade aufgefallen ist:

Es sind ALLE LeiterInnen, die wir haben, die KEINE Rolle auf JS-Baeretswil-Ebene haben. Fröschli-Stufe ist nicht betroffen. Demfall hat es etwas zu tun mit der "Stufe". Stufenleiter sind nicht betroffen.
Wenn ich nun einer Leiterin eine Rolle auf JS-Ebene gebe, dann erscheint sie im Abo-Export. Wenn ich die Rolle wieder entferne, ist sie nicht mehr im Abo-Export.

**Comment by maede97** [comment]
Ups. Mein Fehler... Auf der Produktiv-Instanz habe ich das Häckchen statt bei GL bei Helfer gesetzt....
