### ISSUE TITLE
Dokumentation von Freigabe-Funktion

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#112]
Die Freigabe-Funktion für Personen-Daten sollte noch dokumentiert werden.
Meine Notizen bis jetzt (aus Sicht einer OG):
- Es gibt sie an 2 Orten (JS Level und OG Level). Sie wirkt sich je nur auf die Ebene aus.
- Sie wirkt beim hinzufügen von Personen in andere OG Stufen. Sie wirkt auch beim hinzufügen von Personen in Lager von anderen OG (getestet).
- Sie wirkt NICHT bei Kursen und innerhalb der eigenen OG.

**Comment by nchiapol** [comment]
* Sie wirkt ebenfalls nicht bei Gruppen der eigenen Region (Zugriffsrecht: `:layer_and_below_...`).
* Sie wirkt bei Gruppen und Kursen des Cevi Schweiz (Zugriffsrecht: `:layer_...`).
* Massgebend dafür ob und an wen die Anfragen gehen ist die Hauptgruppe (dunkler Stern bei den Rollen) der Person.
