### ISSUE TITLE
Personenliste - Zusätzliche Spalten leer

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#118]
https://db.cevi.ch/groups/92/people?returning=true

Dann als zusätzliche Spalte "Beruf/Klasse" auswählen.
Diese Spalte bleibt leer, auch wenn Daten erfasst sind.

**Comment by wp99cp** [comment]
Als Ergänzung: Die Spalte is nur leer, wenn zusätzlich ein Filter ausgewählt wird. Nach einem Klick auf "Mitglieder" werden die Daten in der Spalte wieder angezeigt.


![image](https://user-images.githubusercontent.com/34008738/115027595-2ff07b00-9ec4-11eb-97f1-94404be57274.png)

vs.

![image](https://user-images.githubusercontent.com/34008738/115027784-69c18180-9ec4-11eb-8af2-952a1adb521d.png)

**Comment by nchiapol** [comment]
scheint unterdessen zu funktionieren
