### ISSUE TITLE
Spenderrollen sollen nicht angezeigt werden

### ISSUE THREAD

**Issue by smathys** [cevi/hitobito_cevi#12]

**Comment by btemperli** [comment]
Für wen genau soll die Spenderrolle sichtbar sein? Oder soll diese ganz ausgeblendet werden?

**Comment by nchiapol** [comment]
Bei den Rollen einer Person sollte die Spender-Rolle nur angezeigt werden, wenn der Betrachter auch die Personenliste der entsprechenden Spendergruppe sehen könnte. (Und die Personenliste sollten leer sein, auch wenn ich auf einzelne Mitglieder sonst schon Zugriff hätte.)

**Comment by nchiapol** [comment]
vgl. aktuell auch https://github.com/hitobito/hitobito_cevi/issues/39, evtl. kann dieses Issue gleich mit berücksichtigt werden, wenn der Bug korrigiert wird

**Comment by MrTinnysis** [comment]
https://github.com/hitobito/hitobito_cevi/commit/3949a9efb01922f43592f26b6cb6825683844ee7

**Comment by MrTinnysis** [comment]
Habe dies erfolgreich in der integration getestet.
