### ISSUE TITLE
Layout issue error page 500

### ISSUE THREAD

**Issue by btemperli** [cevi/hitobito_cevi#135]
Die beiden Links "Anmelden" sowie "Passwort vergessen" werden auf der Fehlerseite (500) hinter dem Logo angezeigt.

<img width="847" alt="layout-issue_anmelden-passwort-error" src="https://user-images.githubusercontent.com/3005632/146025600-4ad5bdfc-eb0c-4116-b0ed-4363cd89c775.png">

**Comment by nchiapol** [comment]
Ist wahrscheinlich das gleiche Problem wie https://github.com/hitobito/hitobito/issues/1475 schliesse das deshalb hier.
