### ISSUE TITLE
Bemerkungen in TN-Liste für Küche

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#138]
Anliegen von Amigo:

> Ich wollte fragen, ob es möglich ist, bei den Teilnehmern eines Events in
> der Spaltenauswahl auch die Bemerkungen einzublenden? Oftmals stehen dort
> wichtige Informationen, für allem für die Küche, wie Allergien, spätere An-
> bzw. frühzeitige Abreise, und die Küche kommt mittels Export nicht an diese
> Angaben. So muss ich als Kursleiter daran denken, den Export für die Küche

Gedanke: Die Bemerkungen könnten auch persönliche Details enthalten, die für die Küche nicht relevant sind (Bettnässer, psychisches Leiden, Infos zu familiärer Situation, ...). Ich glaube es ist deshalb korrekt, wenn dieses Feld zuerst von der Hauptleitung geprüft wird, bevor die Infos an die Küche weitergeleitet werden.

**Comment by tschuepbach** [comment]
Test auf Integration:
Im Export von Personen mit der Rolle "Küche" wird die Spalte Bemerkungen ebenfalls mit einbezogen. Lediglich "interne Bemerkungen" werden nicht exportiert. (Nur mit der Rolle "Küche" getestet.)

Anlass: https://cevi.puzzle.ch/groups/6/events/1157
Person-Küche: https://cevi.puzzle.ch/groups/414/people/3103

Selbes Schema für Kurse.

-------------------------
Weiter könnten Infos für die Küche wie Anmeldeangaben abgefragt werden. Diese können alle Leitungspersonen via Spalten einblenden.

**Comment by nchiapol** [comment]
vorerst nichts geplant.
