### ISSUE TITLE
Bearbeitungsrechte von Kursleitern und Gruppenleitern

### ISSUE THREAD

**Issue by stymphalide** [cevi/hitobito_cevi#147]
Beliebige Leiter, die in ihrer Gruppe (oder Kurs) in einem Bearbeitungsrechte haben können fremde Personen zu ihrer Gruppe (oder Kurs) hinzufügen und alle Daten sehen und bearbeiten. Und zwar jede Person, die man mit Namen finden kann, in der gesamten Datenbank.

Meiner Meinung nach sollte man höchstens Lesezugriff (auch kann man ähnlich wie bei Kursteilnehmern einschränken) erhalten bzw. die hinzugefügte Person soll den Bearbeitungszugriff aktiv erteilen müssen.

**Comment by nchiapol** [comment]
Der Zweck der CeviDB ist, dass Daten gemeinsam verwaltet werden können. Dabei ist oft unklar welche Gruppe die Hauptverantwortliche für die Daten sein sollte. Entsprechend muss es möglich sein, bestehende Personen zu eigenen Gruppen hinzuzufügen und zu bearbeiten.

Die Missbrauchsgefahr kann via Zugriffsanfragen minimiert werden:
  vgl. https://hitobito.readthedocs.io/de/latest/access_concept.html#security-zugriffsanfragen-und-manuelle-freigabe
