### ISSUE TITLE
Abos basierend auf Qualifikationsfilter

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#15]
Beim Versand der Mails (=Abos) sollte auch ausgewählt werden können, dass auf einer Ebene auch Personen mit einer Qualifikation angeschrieben werden können (z.b. J-S-Leiter). Momentan sind nur Rollen möglich.

**Comment by smathys** [comment]
@maede97 kannst du das hier noch ein wenig ausformulieren, damit auch aussenstehende Cevianer wissen was wir mit diesem Issue bewirken möchten?

**Comment by maede97** [comment]
Jetzt überprüft, fehlt noch immer

**Comment by nchiapol** [comment]
existieren jetzt
