### ISSUE TITLE
Nationale Angestelltenkonferenz war in Suche nicht sichtbar

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#150]
Die nationale Angestelltenkonferenz war für einzelne Personen/zu bestimmten Zeiten in der Suche oben nicht sichtbar. 
Möglicherweise hat das einen Zusammenhang mit den eingeschränkten Zugriffsrechten des Dachverbands.

**Comment by tschuepbach** [comment]
Ich konnte den Anlass auch nicht finden über die Suche.
Allenfalls lag es an folgender Einstellung:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/40494600/170232370-0dcbaa95-545b-4604-a3bd-7dfc18bfa3fe.png">

**Comment by nchiapol** [comment]
Ich schliesse dieses Issue. Es gab seit über einem Jahr keine relevanten weitere Vorkommnisse oder Infos.
