### ISSUE TITLE
Rechnungen: Rechnungstext durch Mahntext ersetzen.

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#156]
Die Geschäftsstelle der Region Zürich hat gewünscht, dass bei Mahnungen der ursprüngliche Rechnungstext nicht mehr angezeigt wird.

Ich bin nicht sicher, ob das sinnvoll/richtig ist. Auslöser des Problems ist eine Kursrechnung, bei der der Rechnungstext vom bevorstehenden Kurs spricht: "Wir freuen uns, dich schon bald in unserem Kurs begrüssen zu dürfen. Wir wünschen dir viel Spass!"
Dieser Text könnte auch problemlos so formuliert werden, dass er auch auf einer Zahlungserinnerung passt. ("Vielen Dank, dass du dich für unseren Kurs angemeldet hast.")

Wird das Verhalten hier angepasst, müsste beim Formulieren des Texts das Verhalten ebenfalls berücksichtigt werden, da dann keine für die Zahlung relevante Informationen enthalten sein dürfen. 
Das aktuelle Verhalten scheint mir weniger problematisch.

**Comment by tschuepbach** [comment]
Ich bin auch der Meinung, dass der Text "neutral" formuliert werden kann. Zudem erachte ich persönlich dies als "vertretbar", sollte jemand einen Zahlungserinnerung mit oben formulierten Text, nach dem Kurs erhalten. Dieser Person wird ja klar sein, dass er*sie die Rechnung noch nicht bezahlt hat und der Kurs ggf. schon stattgefunden hat.

**Comment by nchiapol** [comment]
an Meeting besprochen
