### ISSUE TITLE
Kurse: Anmeldung automatisch schliessen

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#157]
Die Geschäftsstelle der Region Zürich hat gewünscht, dass bei Kursen bei denen die Anmeldefrist abgelaufen ist, der Status automatisch auf "Anmeldung abgeschlossen" umgestellt wird.

Einschätzung Carbon: Falls das implementiert wird, müsste das auf jeden Fall konfigurierbar sein. Ich glaube, in den allermeisten Fällen entspricht das aktuelle Verhalten der Realität und verursacht weniger Arbeit. 
Solange in Kursen noch Platz ist, werden wir TN auch nach dem Anmeldeschluss nicht abweisen. Wenn sich jede Person, die die Frist um ein paar Tage verpasst, bei der Geschäftsstelle meldet, wird das bestimmt mehr Aufwand generieren.
Zudem Schätzt eine solcher Automatismus weder gegen verspätete Anmeldungen mit dem Papierformular noch per Mail.

**Comment by tschuepbach** [comment]
Sicht GS CCH:
Bei uns wird die Anmeldung oft in Absprache mit der Kursleitung geschlossen. Die Anmeldefirst ist dabei ein ungefährer Richtwert. Meist wird am/nach Anmeldefrist gemeinsam besprochen, ob wir die Anmeldung noch offen lassen oder schliessen.
Wir könnten sicherlich mit beiden Varianten leben, bin aber auch der Meinung, dass dies konfigurierbar sein müsste.

**Comment by nchiapol** [comment]
wird nicht umgesetzt, die Flexibilität ist wichtiger als die automatisierung
