### ISSUE TITLE
Version 1.28 fehlt im Changelog

### ISSUE THREAD

**Issue by patrickuhlmann** [cevi/hitobito_cevi#160]
Unten auf der Seite wird die Version mit 1.28 angegeben. Im Changelog gibt es jedoch nur einen Eintrag für Version 1.27. Kann man da die aktuelle Version noch ergänzen?

**Comment by maede97** [comment]
Eigentlich wird der Changelog von Hitobito nachgeführt. Auf der Test-Umgebung https://cevi.puzzle.ch/changelog ist auch alles richtig nachgeführt. Ich glaube, mit dem nächsten Release auf unsere Produktiv-Instanz sollte dann alles stimmen.

**Comment by patrickuhlmann** [comment]
Unterdessen ist es korrekt nachgeführt.
