### ISSUE TITLE
Bearbeitung der eigenen Kursanmeldung

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#163]
Die Möglichkeit nach dem Abschicken der Kursanmeldung diese nochmals bearbeiten zu können.

**Comment by maede97** [comment]
Es können nur die Kontaktangaben geändert werden.
Probleme mit Änderungen: Änderungen können eventuell übersehen werden.

**Comment by nchiapol** [comment]
Ist schon spät... habe falschen Kommentar gelöscht

An Treffen diskutiert:
-   use-case unklar.
-   ist heikel. Änderungen könnten passieren ohne, dass die relevanten Personen das mitbekommen.
