### ISSUE TITLE
Suchfunktion zeigt immer max 10 Einträge

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#166]
Hallo zusammen

Ich versuche gerade anhand unseres Datenplans zu überprüfen, ob der Cevi Schweiz nationale Termine in der cevi.db eingetragen hat.
Leider werden nicht immer alle Ergebnisse angezeigt, was ein wenig mühsam ist.

Ich Suche nach „ coachkurs“ und versuche festzustellen, ob das Datum für das Jahr 2023 bereits fixiert ist.
Leider finde ich mit dieser Suche keinen Coachkurs im Jahr 2023.

Wenn ich aber nach „coachkurs 2023“ suche, finde ich einen Kurs.

Wieso werden bei der allgemeineren Suche die gewünschten Anlässe ausgeblendet?

**Comment by maede97** [comment]
Laut Tests werden immer 10 Treffer angezeigt (max).
Also in der Suche (Dropdown) sowie auch nachher in der ausgeführten Suche auf der werden strikt nicht mehr als 10 angezeigt.

- [ ] Die Suche soll (nach klick auf das Such-Icon) sicher alle Inhalte mit dem Suchbegriff anzeigen.

**Comment by nchiapol** [comment]
upstream bug (https://github.com/hitobito/hitobito/issues/827) kommentiert und in Bug-Sammlung ergänzt
