### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#167]
Ich erfasse hier mal meine Erkenntnisse der aktuellen Tests. Mache dies bewusst nicht auf hitobito/hitobito_cevi, da vlt. nicht alles für hitobito relevant ist; und zwecks Nachverfolgung nicht per Mail

**Comment by tschuepbach** [comment]
Events: AHV- & J+S-Nummer auf Personen anzeigen funktioniert aus meiner Sicht wie gewünscht.

see https://github.com/hitobito/hitobito_cevi/issues/98

**Comment by tschuepbach** [comment]
**Events: gleiche Rechte für Hauptleitung**

Auf dem Tab "Anmeldungen" fehlen der Hauptleitung folgende Funktionen:

Person noch nicht zugeteilt (rechte Spalte)
- Ablehnen
- Anmeldung löschen

Person zugeteilt (linke Spalte)
- Anmeldung löschen

Dass "Anmeldung löschen" fehlt, ist aus meiner Sicht vertretbar; "Ablehnen" sollte aus meiner Sicht für die Kursleitung verfügbar sein.

see https://github.com/hitobito/hitobito_cevi/issues/89

**Comment by nchiapol** [comment]
Ich habe die Anliegen weitergeleitet.
