### ISSUE TITLE
es werden persönliche Daten im Log angezeigt

### ISSUE THREAD

**Issue by smathys** [cevi/hitobito_cevi#17]
Müssen private Daten
Mailadressen
Adresse
Telefonnummern
im Log für alle Ewigkeit gepseichert werden und ersichtlich sein?
Es kann sein, dass wir hier Daten speichern, wo keine Einwilligung des Eigentümer vorliegt.
Personen können zwar ihre Daten verändern, durch die Ansicht im Log werden diese Daten aber nicht dauerhaft gelöscht/entfernt.

**Comment by smathys** [comment]
Wichtig, das Log sehen nur Personen. welche deine Angaben sehen können, das heisst sie hätten deine alte Mailadresse und Telefonnummern sowieso gesehen als die aktiv in den Daten angezeigt waren.
Das erfassen der Daten wird in den Ortsgruppen verwaltet, die können ja auch ihre Mitglieder aktiv fragen, welche Daten in der DB gespeichert werden sollen. Ein weiterer Punkt den du ansprichst wäre noch, dass evtl. die Log Einträge nicht von aller Ewigkeit angezeigt werden müssen, dass z.b. nur die letzten 2 Jahre angezeigt werden.

**Comment by nchiapol** [comment]
Einfacher Lösungsansatz: Log nur für die letzten 3 (6?, 12?) Monate anzeigen.

**Comment by kronn** [comment]
Das Einschränken auf bestimmte Attribute ist schwer und fehleranfällig. Besser fände ich auch, die Anzahl der gespeicherten Versionen zu beschränken. Es gibt hierfür zwei Ansätze:
- Beschränkung auf die letzten n (10? 20?) Einträge. Wenn eine neue Änderung kommt, durch eine neue Rolle oder so, würde das älteste rausfallen. Damit wären bei den meisten dann genau 10 oder 20 Einträge vorhanden.
- Regelmässiges Löschen aller Einträge die älter als (3? 6? Wochen? Monate?) sind. Damit wären bei vielen nach dieser Zeit keine Einträge sichtbar. 

Da beides Abwägungen zwischen Nutzen und Privatsphäre sind, hätte ich gerne eure Antwort dazu. Letztlich könnt ihr das besser beurteilen.

Wenn nur bestimmte Felder entfernt werden sollen, geht das natürlich auch. Das Bereinigen der alten Einträge ist jedoch aufwendig. Ich bräuchte in dem Fall eine Richtlinie, welche Art von Daten ich nicht im Log aufnehmen und aus den alten Einträgen bereinigen soll.

**Comment by btemperli** [comment]
Danke fürs Anschauen und deine Einschätzung!

Ich würde Einträge im Log nach 6 oder 12 Monaten (über die Zeit lässt sich noch diskutieren) entfernen (oder zumindest nicht mehr anzeigen).
Bei einer Beschränkung auf n Einträge kann es doch vorkommen, dass 10 Jahre alte Einträge sichtbar bleiben.

Aber das ist mal meine Meinung, was meinen die Anderen?

**Comment by nchiapol** [comment]
Ich teile @btemperli's Einschätzung. Ich würde auch die Zeit und nicht die Anzahl Einträge verwenden. Mit der Anzahl könnten Änderungen nicht nur viel zu lange sondern auch extrem kurz sichtbar bleiben (Ich kann das Log dann einfach mit Einträgen fluten.)

Wie auch von @btemperli angetönt, würde ich zudem die Daten lieber (noch) nicht löschen sondern vorerst einfach nicht mehr anzeigen. So können wir über die nächsten Monate Erfahrungen sammlen und dann allenfalls die Regeln noch anpassen.
Falls das möglich ist, würde ich wohl nur 3 Monate wählen, so zeigen sich dann allfällige Probleme hoffentlich rasch.
