### ISSUE TITLE
ABO: Probleme seit Umstellung auf neuen Mailstack?

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#178]
In der Region Bern tritt seit der Umstellung vorletzten Dienstag folgendes Problem auf:

Empfänger*innen Abo: z.B. alle aktiven Ortsgruppenleitenden
Ebene Abo: Cevi Region Bern
Zusätzlicher Absender: mail@ceviregionbern.ch (geteiltes Postfach)

Das Mail an die Abos werden von der allgemeinen Mail mail@ceviregionbern.ch versendet.

**Probleme:**
- Alle vom Seki-Team erhalten die Verandsbestätigung auf das persönliche Mail
- Falls jemand vom Seki-Team eine Abwesenheitsmeldung im Outlook aktiviert hat (ausserhalb der Organisation) und zugleich Empfänger*in des Abos ist, wird die Abwesenheitsmeldung an **alle** Empfänger/-innen vom Abo versendet. Diese tauchen anschliessend auch in der DB als eigenständiges Mail ans Abo auf:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/40494600/236274156-c07eef39-c3d4-457d-80ff-ce58c124dce3.png">

Kann jemand eruieren, woran das Problem liegt oder soll ich dies an hitobito weiterleiten?

Es kann sein, dass am geteilten Postfach liegt, aber vor der Umstellung am 25.04.2023 trat dieses Problem nicht auf..

**Comment by nchiapol** [comment]
> Alle vom Seki-Team erhalten die Verandsbestätigung auf das persönliche Mail

Das ist eine Frage eurer Mail-Client Einstellungen - wahrscheinlich ist in den Mails von mail@ceviregionbern.ch die Reply-To entsprechend gesetzt.

>  Falls jemand vom Seki-Team eine Abwesenheitsmeldung im Outlook aktiviert hat (ausserhalb der Organisation) und zugleich Empfänger*in des Abos ist, wird die Abwesenheitsmeldung an alle Empfänger/-innen vom Abo versendet. Diese tauchen anschliessend auch in der DB als eigenständiges Mail ans Abo auf

https://github.com/hitobito/hitobito/issues/2080

Allerdings: Wenn die Abonnenten nicht auf das Abo senden dürfen, sollte das in meinen Augen nicht möglich sein.
