### ISSUE TITLE
Einstellungen: Qualifikations-, Kursarten und -kategorien

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#179]
Hallo zusammen

Ich sehe aktuell bei den Einstellungen die Qualifikations-, Kursarten und -kategorien nicht mehr. Screenshot Produktion:
<img width="199" alt="image" src="https://github.com/cevi/hitobito_cevi/assets/40494600/7c2e2561-4081-4876-a3b8-c39cd65242db">

Selbes Problem auf der Testumgebung..

Ist dies bei euch auch so?

Hängt dies allenfalls mit dem pull request bezüglich den admin-Rechten zusammen? 🤔

**Comment by nchiapol** [comment]
Sieht bei mir gleich aus.

> Hängt dies allenfalls mit dem pull request bezüglich den admin-Rechten zusammen?
Sehr unwahrscheinlich. Das war ein 1-line Change nur bei den MIO admins. Wir haben aber beide Dachverbandsadmin Rollen und die haben nach wie vor die :admin abilitiy.

Mach bitte ein Ticket im Repo von Puzzle.

**Comment by nchiapol** [comment]
Forwaded as: https://github.com/hitobito/hitobito/issues/2113
