### ISSUE TITLE
Anpassungen infolge DSE

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#186]
Hallo zusammen

Im Zusammenhang mit der Erarbeitung der neuen DSE für den Cevi Schweiz möchten wir folgende Verbesserungsvorschläge machen.

Prämisse (Auszug aus der DSE-Wegleitung für die Abteilungen):
![dse](https://github.com/cevi/hitobito_cevi/assets/40494600/886947a2-0e31-4de6-ac76-d687802ac77d)

Finanzierung tbd

**Comment by tschuepbach** [comment]
### AHV-Nummer

`AHV-Nummer alt` wird gelöscht
`AHV-Nummer` wird in die Events verschoben und dort anschliessend automatisch wieder gelöscht

see https://github.com/hitobito/hitobito/issues/2162

**Comment by tschuepbach** [comment]
### Konfession

Wir schlagen vor, das Personenattribut `Konfession` zu belassen, da dies von Abteilungen für effektive Zwecke (und mit Zustimmung, z.B. Uster) verwendet wird.

Mögliche Anpassungen:
- [ ] Analog `Zusätzliche Angaben` einen entsprechenden Text ergänzen. Beispiel: _Besonders schützenswerte Daten, wie die Konfession, dürfen nur für plausibel begründete Zwecke erfasst und gespeichert werden. Dazu ist vorgängig eine Einwilligung einzuholen._
- [ ] Falls umsetzbar: Den anzuzeigenden Text als "Hover-Text" implementieren

**Comment by tschuepbach** [comment]
### Notizen & Tags

Allenfalls selben Hinweistext wie bei `Zusätzliche Angaben` ergänzen.

**Comment by tschuepbach** [comment]
### Gesundheitsdaten / Allergien

Können und sollten nur in den Events erfasst werden. Ticket für die automatisierte Löschung besteht bereits, see https://github.com/hitobito/hitobito/issues/2129.

**Comment by patrickuhlmann** [comment]
> * Analog `Zusätzliche Angaben` einen entsprechenden Text ergänzen. Beispiel: _Besonders schützenswerte Daten, wie die Konfession, dürfen nur bei konkreter Notwendigkeit erfasst und gespeichert werden. Dazu ist vorgängig eine Einwilligung einzuholen._

Möchten wir dort nur Konfession schreiben? Ich hätte auch die Gesundheitsdaten und allenfalls sogar Allergien speziell erwähnt da es wohl häufig genau dafür verwendet wird und diese eventuell nicht jeder automatisch als "besonders schützenswert" betrachtet.

**Comment by nchiapol** [comment]
@patrickuhlmann einverstanden, guter Hinweis.

**Comment by nchiapol** [comment]
Geplantes Vorgehen:
  - klären was von Jubla/Pfadi übernommen werden kann
  - gemeinsam mit anderen Anliegen priorisieren.

**Comment by nchiapol** [comment]
Für die Hinweistexte möchten wir https://github.com/hitobito/hitobito/issues/2686 umsetzen lassen. Die anderen Anliegen hier werden ebenfalls durch separate Tickets erledigt. Ich schliesse dies deshalb.

Referenzen:
* https://github.com/hitobito/hitobito_youth/issues/59
* https://github.com/hitobito/hitobito_youth/issues/58
* https://github.com/hitobito/hitobito/issues/2129
