### ISSUE TITLE
Unter "Kein Login?" ist AG-SO-LU-ZG nicht aufgeführt

### ISSUE THREAD

**Issue by patrickuhlmann** [cevi/hitobito_cevi#191]
Vermutlich handelt es sich beim angezeigten Text um eine Konfiguration die wir selber machen können unter Einstellungen/Texte/Login Informationen/.

Aktuell:
![image](https://github.com/cevi/hitobito_cevi/assets/511373/15141e3e-8f7a-4f6f-9c05-4ea37ead3143)

Folgende Ergänzung wäre notwendig:
5. AG-SO-LU-ZG - [Seki](mailto:seki@cevi-agsoluzg.ch)

**Comment by nchiapol** [comment]
Habe ich eben erledigt - einfach mit der Mail-Adresse statt "Seki" als Link-
Text.
