### ISSUE TITLE
Personenfilter | Suche nach Beruf

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#192]
> Gibt es eine Möglichkeit Personen nach ihrem Beruf zu filtern?
> Dies würde uns helfen Personen nach Fachwissen anzufragen. In unserem Fall geht es um eine Person mit Fachwissen im Bereich Personalverantwortung.
>Leider kann ich beim aktuellen Filter unter Felder nicht nach Beruf filtern. 

Anfrage Curador 30.11.2023

**Comment by nchiapol** [comment]
- Aktuell keine Priorität
- Datenqualität wäre eine Herausforderung (ist ein Freitext-Feld)
- "Workaround": Spalte Beruf einblenden und Liste der Personen exportieren, so kann im Excel durchsucht werden
