### ISSUE TITLE
"Statistik" zu "Bestandesmeldungen" umbenennen

### ISSUE THREAD

**Issue by patrickuhlmann** [cevi/hitobito_cevi#199]
So sieht es aktuell aus:
![image](https://github.com/cevi/hitobito_cevi/assets/511373/93240ea0-e685-4467-bc70-76adc4afdf76)

Im Tab Statistiken wird die Anzahl Personen pro Jahrgang angezeigt. Im Tab Statistik die Personen nach Mitgliederorganisation. Auf dem Bildschirm Statistik wird von Bestandesmeldungen gesprochen.

Vorschlag: Den Tab Statistik nach Bestandesmeldungen umbenennen. Sowohl auf Ebene Cevi Schweiz wie auch auf Ebene Mitgliederorganisationen

**Comment by nchiapol** [comment]
In der aktuellen Form ist das Tab "Statistiken" zudem nicht sehr hilfreich. Es werden immer einfach alle Kontakte der ganzen Ebene angezeigt (inkl. Externer). Aus meiner Sicht könnt das auch ganz deaktiviert werden. 

"Bestandesmeldung" wäre sehr lang für ein Tab - evtl. einfach "Bestand" verwenden?
