### ISSUE TITLE
Dublette bei PLZ-Änderung

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#2]
Falls eine Person neu importiert wird, bei der die PLZ anders ist, gibt es eine Dublette.
Reproduktion:
- Die Person Peter Pan lebt an der Flugstrasse 1 in **8000** Zürich.
- Er ist nun gezügelt an die Landstrasse 5 in **8001** Zürich.
- Der Adressverwalter von Peter hat seine Adresse in der DB nicht geändert.
- Bei einem neuen Import von Adressen wird es einen neuen Peter Pan geben.
Schlussfolgerung: Die Dubletten-Erkennung funktioniert bei allem ausser der PLZ.
Mein Vorschlag: Die CeviDB gibt eine Warnung beim Import aus, dass zweimal die gleiche Person existiert, welche in Orten mit verschiedenen PLZ wohnt. Dann kann der Importeur kontrollieren und eventuell die Dublette vermeiden.

Dubletten lassen sich ja nur sehr schlecht löschen (siehe dazu #1)
| Scirocco

**Comment by smathys** [comment]
Dieses Thema werde ich nach dem Haushaltsadressierungs-Feature mit Hitobito anschauen, kann mir vorstellen, dass die Änderung bei ihnen nicht trivial sein wird.

**Comment by nchiapol** [comment]
import ist low-prio -> wontfix
