### ISSUE TITLE
Link zu Datenschutz-Merkblatt in den Nutzungsregeln der Login-Seite ist ungültig

### ISSUE THREAD

**Issue by wp99cp** [cevi/hitobito_cevi#202]
Der Link zum Datenschutz-Merkblatt für Vereine ist nicht mehr gültig. Der Text auf der Login-Seite sollte angepasst werden.

> ## Nutzungsregeln
> Wenn du dich in die CeviDB einloggst, verpflichtest du dich gleichzeitig die folgenden Regeln einzuhalten:
> [...]
> Du hältst dich an die [Anforderungen des Datenschutzses](https://www.edoeb.admin.ch/edoeb/de/home/datenschutz/dokumentation/merkblaetter/umgang-mit-mitgliederdaten-in-einem-verein.html).

Ggf. lässt sich der Link mit dieser Seite austauschen: 
https://www.edoeb.admin.ch/edoeb/de/home/datenschutz/freizeit_sport/datenbearbeitung_vereine.html

Oder wir verweisen auf ein Cevi internes Merkblatt, gibt es da etwas entsprechenden? Reicht hier https://www.cevi.ch/datenschutz/?

**Comment by nchiapol** [comment]
Vielen Dank für den Hinweis und den neuen Link. Habe vorerst die Startseite mit dem neuen Link des EDOEB aktualisiert. Ob wir beim Login zusätzlich auf die Datenschutzerklärung verweisen wollen, werden wir noch diskutieren.
