### ISSUE TITLE
Freigabemail an die Coaches wird nicht versendet

### ISSUE THREAD

**Issue by patrickuhlmann** [cevi/hitobito_cevi#207]
Siehe Upstream Issue https://github.com/hitobito/hitobito/issues/2120.

Meldet sich ein Teilnehmer an einem Kurs, wo die Option " Der Coach wird informiert und muss die Anmeldung bestätigen" aktiviert ist, erhält der Coach aktuell kein E-Mail.

**Comment by nchiapol** [comment]
Das upstream issue ist bereits unter #131 aufgeführt. Ich glaube wir brauchen kein separates Issue in unserem Tracker.
