### ISSUE TITLE
Update Dokumentation Elternzugang

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#209]
Mit https://github.com/hitobito/hitobito_youth/pull/44 hat sich das Interface für Verwaltungsbeziehungen geändert. 

![screenshot_2024-03-24_214258](https://github.com/cevi/hitobito_cevi/assets/1123483/e5815ca7-3e09-433c-9d37-a60cf493feba)

Die Dokumentation müsste entsprechend nachgeführt werden.

@tschuepbach Kann sich wieder euer Zivi darum kümmern?

**Comment by tschuepbach** [comment]
Yes, Updates sind schon vorbereitet und werden am 02. April veröffentlicht. 👍🏽

**Comment by nchiapol** [comment]
perfekt, danke!
