### ISSUE TITLE
Benachrichtigung über neue Online-Anmeldungen

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#22]
Am besten wohl 1x am tag, falls es ebe neue hat, um so eine Flut von Mails zu vermeiden. So könnte er das Versenden der TN-Infromationen schneller und einfacher handhaben.
(Wunsch von Popcorn, 19.1.15)

**Comment by nchiapol** [comment]
Der Wunsch nach E-Mail-Benachrichtigungen besteht auch bei der GS des Cevi Schweiz.

**Comment by btemperli** [comment]
Siehe auch https://github.com/hitobito/hitobito/issues/1133

**Comment by nchiapol** [comment]
fixed
