### ISSUE TITLE
EVENTS: Sortierung nach Rolle führt zu 500er 

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#233]
Ich habe soeben festgestellt, dass die Sortierung nach Rolle in einem Event zu einem 500er führt. Egal, bei welcher Ansicht:
<img width="743" alt="image" src="https://github.com/user-attachments/assets/b2161728-48b3-4544-8668-c88177abb98d">

Ich konnte das Problem nur auf der Produktivumgebung nachstellen, in der Testumgebung funktioniert alles wie gewünscht. Macht es Sinn, den Bug trotzdem weiterzuleiten?

**Comment by patrickuhlmann** [comment]
Müsste man vermutlich noch etwas genauer eingrenzen. Ich habe selber auf Produktion kurz die Sortierung nach Rolle ausprobiert auf Gruppen, Anlässen und Kursen und bei mir hat es ohne Fehler funktioniert. Auf welchem Event hast du es versucht? Ist möglicherweise nur dieses Event betroffen?

**Comment by tschuepbach** [comment]
Auf verschiedenen Events, lustigerweise funktioniert nun alles wie gewohnt.
