### ISSUE TITLE
CSV-Import: Name != Ceviname

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#27]
Beim CSV-Import wird die Spalte "Name" standardmässig mit Ceviname verknüpft. Nachname wäre sinnvoller.

**Comment by maede97** [comment]
Funktioniert auf dem Produktiv sowie auf dem Test-System. --> closed

**Comment by maede97** [comment]
Geht doch noch nicht.

Falls Spalten "Vorname", "Nachname", "Ceviname" heissen, dann geht es.
Falls aber die Spalten "Name", "Nachname", "Ceviname" heissen, geht es nicht.

**Comment by nchiapol** [comment]
forwarded aber nicht wichtig genug um im eigenen Tracker zu behalten.
