### ISSUE TITLE
Personen-Attribut "Ortsgruppe" lässt sich nicht löschen

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#3]
Wurde bei einem Kontakt eine Ortsgruppe ausgewählt, kann sie nur durch eine andere ersetzt, nicht aber ganz gelöscht werden.

**Comment by kronn** [comment]
![remove-ortsgruppe](https://user-images.githubusercontent.com/72198/100633262-2956d200-332e-11eb-9e64-a07fac2baf10.png)

Mittlerweile kann man durck Klick auf das kleine "x" am rechten Rand die Auswahl von Kanton und Ortsgruppe entfernen. Dies lässt sich dann auch speichern. 

Ich bin unsicher, seit wann das schon möglich ist.

**Comment by nchiapol** [comment]
Stimmt das funktioniert für mich auf der Integrationsumgebung ebenfalls.
