### ISSUE TITLE
Freitextfeld bei Gremien

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#31]
Ein Freitextfeld "Beschrieb" bei allen Gremien würde erlauben, weitere Infos über einem Gremium zu hinterlegen. Das wäre zum Beispiel für Projekt-Gremien sehr nützlich um das Projekt genauer zu beschreiben.

Popcorn möchte bei den APGs z.B. folgende Dinge hinterlegen:
- Kurzbeschreibung des Ziels der APG
- Gründungsdatum und -gremium [fürs Datum gibt es bereits ein separates Feld]
- Ziele und Massnahmen
- Interessierte Gremien
- Nächster Schritt
- Termin bis nächster Schritt erledigt wird

Für einzelne Felder sind das wohl zu spezifische Wünsche. Ein Freitextfeld würde das aber abdecken. Perfekt  wären natürlich Formatierungsmöglichkeiten (Markdown-Support).

**Comment by btemperli** [comment]
Neu (oder auch nicht so neu) gibt es bei den Gremien

- Beschreibung
- Gründungsdatum

Reicht das bereits und kann das Ticket dementsprechend geschlossen werden? /cc @nchiapol
