### ISSUE TITLE
Möglichkeit Gremien zu Archivieren

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#32]
Gerade bei Projektgremien (APGs) besteht der Bedarf, diese irgendwann zu schliessen und zu archivieren. Wenn das Gremium gelöscht wird, sind die ehemaligen Mitglieder danach nicht mehr verknüpft und können deshalb nicht mehr einfach bestimmt werden.

**Comment by MrTinnysis** [comment]
Evtl. mit Änderung Grupentyp auf z.b. Archivgruppe
vergleiche https://github.com/cevi/hitobito_cevi/issues/11

**Comment by chrusu** [comment]
![Anlässe mit Einladung Variante B](https://user-images.githubusercontent.com/17568539/116864782-aac9cd80-ac08-11eb-8d3f-558033426224.png)
![Anlässe mit Einladung Variante A](https://user-images.githubusercontent.com/17568539/116864783-abfafa80-ac08-11eb-97ab-9816465308d5.png)

**Comment by chrusu** [comment]
@nchiapol Kurze Frage zum hinzufügen von mehreren Personen. Das 2te Bild basiert auf deinem Vorschlag wenn eine Person hinzugefügt wird. 
Meinem Verständnis nach sollte das "eingeladen"-Attribut nicht die Rolle ersetzen, sondern ergänzen. Entsprechend mein Vorschlag, dieses Attribut loszulösen. Was denkst du dazu?

**Comment by chrusu** [comment]
![Gremien Archivieren Personenansicht2](https://user-images.githubusercontent.com/17568539/116865250-93d7ab00-ac09-11eb-80f3-bcabc5d75074.png)
![Gremien Archivieren Personenansicht](https://user-images.githubusercontent.com/17568539/116865254-94704180-ac09-11eb-95bd-4bc0814d0adb.png)
![Gremien Archivieren Archiviert](https://user-images.githubusercontent.com/17568539/116865258-9508d800-ac09-11eb-817b-188c1c3185f5.png)
![Gremien Archivieren](https://user-images.githubusercontent.com/17568539/116865259-95a16e80-ac09-11eb-8b02-d319989ad4b1.png)
![Gremien Archivieren Schluss](https://user-images.githubusercontent.com/17568539/116865260-95a16e80-ac09-11eb-89ae-af3953ac8847.png)

**Comment by nchiapol** [comment]
Vielen Dank für die Mockups hier. Mir ist nicht überall klar, was du zeigen möchtest.

Zur Anzeige auf der Seite des einzelnen Kontakts: Ich glaube dort sollten archivierte Rollen identisch dargestellt werden wie gelöschte. Aus sicht der "Rolleninhaber" ist ihr Funktion in diesem Gremium in beiden Fällen einfach beendet. Ob das passiert, weil das Gremium nicht mehr existiert oder sie nicht mehr mitarbeiten ist irrelevant.

Bei der Gruppen-Liste scheint mir der letzte Screenshot immer noch die beste Lösung. Das Verhalten mit einer Archiv-Gruppe kann ich dann immer noch manuell umsetzen.

**Comment by chrusu** [comment]
Hallo Nicola, vielen Dank für deine Rückmeldungen. 

Zum Rolleninhaber: Super, dann werde ich die Archivierte Rolle wieder aus dem Profil löschen.

Zur Gruppenliste: Die Idee der Screenshots 3&4 wäre ein automatisiertes Archiv (mit der Anzahl archivierter Gruppen in der Klammer), welches sich auf-/zuklappen lässt um Platz zu sparen.
Falls dir der letzte Screenshot aber reicht ist dies sicher die einfachere Lösung zum umsetzen...

**Comment by nchiapol** [comment]
Update zu Stand:
  - Umsetzung ist in https://github.com/hitobito/hitobito/issues/1275 erfolgt.
  - Bug bei Filtern https://github.com/hitobito/hitobito/issues/1440 macht das Feature aber im Moment noch unbrauchbar.

**Comment by nchiapol** [comment]
done
