### ISSUE TITLE
Evtl. API-Ergänzung

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#39]
Momentan geht die API nur auf Abteilungen. Könnte man diese noch erweitern, damit sie auch auf Kurse/Lager (events) läuft?

**Comment by smathys** [comment]
für das gibt es ein "Feature" request bei Hitobito, events als  json wird wahrscheinlich dieses jahr kommen

**Comment by nchiapol** [comment]
https://github.com/hitobito/hitobito_cevi/issues/18

**Comment by maede97** [comment]
Erledigt.
