### ISSUE TITLE
Provisorische Anmeldung

### ISSUE THREAD

**Issue by MarkusFischerAdler** [cevi/hitobito_cevi#41]
Hallo Roland

Leider habe ich nichts mehr gehört.
Anfang Jahr bestand das Problem gemäss unserem Sekretariat nach wie vor.
Wie ist der Stand und das Vorgehen?

Gruss Markus
________________________________________________________________________________________
Am 02.10.2017 um 15:47 schrieb Roland 

Hallo Markus

Diser Bug ist mir komplett durch die Lappen gegangen. Wir versuchen ihn noch diese Woche zu fixen.

Gruess
Roland
________________________________________________________________________________________
Am 01.10.2017 um 20:40 schrieb Markus

Hallo Roland

Leider habe ich noch keine Rückmeldung erhalten.
Gerne würde ich unsere Nutzer informieren.

Gruss Markus
________________________________________________________________________________________
Am 13.08.2017 um 14:43 schrieb Markus

Hallo Roland

Zu diesem Thema habe ich bei der neusten Version keine Änderung festgestellt.
Wie ist das weitere Vorgehen?

Gruss Markus
________________________________________________________________________________________

Hallo Roland

Aufgrund von Rückmeldungen aus unserem Team eine Präzisierung.
Wird einer Person (welche provisorisch angemeldet ist) eine Teamrolle vergeben, wir die provisorische Anmeldung insofern bestätigt, dass die Person nicht mehr als provisorische Teilnehmerin gilt.
Für den konkreten Fall bedeutet dies wohl nicht Bestätigung der provisorischen Anmeldung sondern Löschung...

Gruss Markus
________________________________________________________________________________________

Hallo Roland

Danke für die schnelle Klärung.
Ich hatte die Ursache in dieser Richtung vermutet, habe es jedoch nicht geschafft dies zu verifizieren.

Wir erfassen potentielle Kursmitarbeiter auch als potentielle Teilnehmer. Daher erscheint mir eine automatisches Bestätigung der provisorischen Anmeldung die richtige Lösung.

Gruss Markus
________________________________________________________________________________________

Hallo Markus

Wir haben das Problem gefunden:

Die Person ist nur provisorisch bei dem Kurs angemeldet. Die Rolle wurde bei jedem Versuch korrekt vergeben: https://db.cevi.ch/groups/3/events/279/participations/12393

Da die Anmeldung nur provisorisch ist, taucht sie in der Liste der definitiven Teilnehmer nicht auf. Und dies eben auch, wenn sie weitere Rollen hat.

Da die Anmeldung ja darauf zielt, Teilnehmer zu sein, ist es vermutlich nicht sinnvoll, bei einer unterstützenden Rolle diese Anmeldung zu bestätigen. Allenfalls könnte es noch sinnvoll sein, die Anmeldung abzulehnen, da die Person durch die unterstützende Tätigkeit eben nicht mehr Teilnehmer ist. Oder eben nur die Person anzuzeigen und so zumindest mehrfache Rollenvergabe zu verhindern. In diesem Fall sollten aber die provisorischen Rollen nicht in der Liste auftreten.

Grundsätzlich sehe ich einen Konflikt zwischen den Rollen Teilnehmer und Küche (in diesem Fall), es betrifft aber vermutlich noch anderen Rollenpaare (wie Leitung und Teilnehmer). 

Was ist hier inhaltlich die richtige Änderung?

- Eine Warnung, dass die Person bereits provisorisch angemeldet ist?
- Eine automatische Bestätigen der provisorischen Anmeldung?
- Eine automatisches Löschen der provisorischen Anmeldung?
- Die Person trotzdem in der Teilnehmerliste anzeigen, unabhängig von anderen Anmeldungen?

Ist jetzt vielleicht ein bisschen technisch aber wir müssen da eine der obenstehenden inhaltliche Anpassung vornehmen. Was würdet ihr erwarten, wenn ihr eine Person die provisorisch angemeldet ist als Helfer aufnehmt, was sollte dann passieren? Die provisorische Anmeldung löschen?
________________________________________________________________________________________

Ok, habe das ausprobiert, und ja es geht tatsächlich nicht.

Sehr eigenartig, dass es die Meldung bestätigt, aber nicht wirklich durchführt. 
Ich kann das morgen gleich mit einem Entwickler anschauen.

Gruss
Roland
________________________________________________________________________________________

Salü Roland

Von unseren Nutzern wurden Probleme beim Vergeben von Kursrollen gemeldet.
Zum Beispiel kann Kelly Langhard / Pena nicht mit der Rolle „Küche“ zum Gruppenleiterinnenkurs 1 hinzugefügt werden. Die Vergabe der Rolle wird zwar bestätigt, jedoch erscheint die Person nicht in der Liste.

Ich habe diverses mit Kursstatus und anderen Einstellungen ausprobiert, kann mir die Ursache aber nicht erklären.

Herzliche Grüsse

**Comment by MarkusFischerAdler** [comment]
Bei provisorisch angemeldeten Personen erzeugt die Vergabe einer Leitungsrolle automatisch die eine Teilnehmerrolle. Dies macht keinen Sinn, da eine Person entweder Leitungsperson oder Teilnehmer ist. Die sonstige Funktion ist in Ordnung.

Klick auf "Anmeldung" erzeugt "500 Internal Server Error"

**Comment by smathys** [comment]
Hallo @MarkusFischerAdler   
Merci fürs nachtesten, ich werde das mit dem 500 internal Server Error auch noch versuchen zu  
 reproduzieren und danach ein Bug erfassen für das Problem mit Leiter automatisch Teilnehmeer, sowie evtl. einen Bug für den 500 Error

**Comment by smathys** [comment]
wird nochmals von Adler getestet auf prod System ob der Fehler behoben wurde

**Comment by MarkusFischerAdler** [comment]
Die Funktion geht weder in Version 1.18.7 (built at: 2018-06-05 12:56:55) noch in Version 1.18.8 (built at: 2018-07-23 17:53:53) korrekt. Klick auf "Anmeldung" erzeugt in beiden Versionen einen "500 Internal Server Error".

**Comment by nchiapol** [comment]
status unklar - provisorische Anmeldungen werden nicht mehr genutzt.
