### ISSUE TITLE
Geändert und Log stimmen nicht überein

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#43]
Bei mindestens einem Kontakt (Rajona, HOM) steht aktuell 
```
Erstellt
24.09.2014 15:14 [...] Cleo (Geschäftsstelle)
Geändert
23.03.2018 08:13 Nicolas [...]
```

der letzte Log Eintrag ist:
```
Dienstag, 13. März 2018, 15:22 Uhr 
von [...] / Sima
```

**Comment by maede97** [comment]
Gleiches geht auch andersum (das heisst, Log ist älter):
Ich habe mir soeben eine neue Rolle in JS Bäretswil gegeben.
`Geändert
04.06.2018 13:50 Matthias Busenhart / Scirocco`
und im Log:
`Dienstag, 19. Juni 2018, 18:44 Uhr
von Matthias Busenhart / Scirocco
Rolle Materialverantwortliche/-r (Vermietung) in JS Bäretswil wurde hinzugefügt.`
