### ISSUE TITLE
Etiketten mit grossen Adressen

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#48]
Wenn viele Personen in einem Haushalt leben (und z.B. die Strasse noch sehr lange ist, werden bei eigenen Etiketten-Formaten einfach die unteren Zeilen abgeschnitten.
Besser wäre es, wenn einfach die Schriftart bei den betreffenden Textfeldern kleiner gemacht wird.
Beispiel für Fehler:
![grafik](https://user-images.githubusercontent.com/14098502/41110152-00bf307e-6a79-11e8-8152-43063b944a19.png)
Adresse wäre: 
![grafik](https://user-images.githubusercontent.com/14098502/41110233-2f83c014-6a79-11e8-9664-7ebee39223a3.png)

**Comment by maede97** [comment]
Früher existiere ja mal noch ein Problem mit den Duplikaten bei Mehrfachsendungen und eigenen Adressen. Dies scheint nun aber behoben zu sein (da mit den Haushalten die Adressierung neu ist)

**Comment by smathys** [comment]
sollte gepatch worden sein
