### ISSUE TITLE
Etiketten nicht immer vollständig

### ISSUE THREAD

**Issue by MrTinnysis** [cevi/hitobito_cevi#50]
Bei Anlässen (aufgefallen bei einem Anlass mit 70+ Personen) sind die Etiketten nicht immer komplett. Manchmal fehlen einige Adressen komplett, manchmal fehlen Personen auf einem Haushaltsetikett.
Ich habe auf die schnelle kein Muster erkennen können.

**Comment by smathys** [comment]
@MrTinnysis  können wir dies auch audience despite testumgebung  auch nachvoll ziehen?

**Comment by MrTinnysis** [comment]
Ich habe den Bug nicht in der Testumgebung nachstellen können. Die Testumgebung hat aber auch schon wieder einen neuere Version.

**Comment by smathys** [comment]
ok, auf der produktiven Umgebung besteht der Anlass noch?

**Comment by MrTinnysis** [comment]
ja

**Comment by smathys** [comment]
und welcher? und waren es standard ettiketten oder ein selbst definiertes Format?

**Comment by MrTinnysis** [comment]
https://db.cevi.ch/groups/1812/events/889/

Zweckform No.L7160 / J8160 (66.0mmx38.1mm) (Globales Etikettenformat)

**Comment by nchiapol** [comment]
Ich habe ebem noch ein weiteres Problem bei den Etiketten festgestellt. Bei "Zweckform No.3658 (64.6mmx33.8mm)" werden immer nur drei Zeilen ausgegeben. Bricht also die Namenszeile um, so fehlt der Ort. (Beobachtet bei diesem Event, aber auch beim Gremien-Abo im RV ZH-SH-GL)

**Comment by maede97** [comment]
Tinguely:
Wenn ich bei unserem Anlass in der Ansicht "Alle Personen" bin und einen Export als Etiketten (im Format Migros Papetteria 7203.112 [globales Format]) anstosse, so wird nur die erste Seite exportiert. Die weiteren Seiten (in meinem Fall die zweite Seite) wird nicht exportiert. Wenn ich jedoch in der Ansicht auf Seite 2 wechsle, so wird diese Seite als Etiketten exportiert.

**Comment by maede97** [comment]
Kommentar zu Anmerkung Tinguely:
Habe dies eben auch noch schnell bei unserem Pfila ausprobiert. Bei uns werden beim gleichen Format alle Adressen ausgegeben.

**Comment by RolandStuder** [comment]
Hallo zäme. Die erwähnten Bugs, kommen offenbar davon, dass wir wegen z. T. grösseren Events eingeführt, haben, dass die Teilnehmer auf mehrere Seiten verteilt werden. Es werden nur die Kontakte auf der aktuellen Seite ausgegeben / zusammengefasst.

**Comment by RolandStuder** [comment]
Das wird resolved mit https://github.com/hitobito/hitobito/pull/629

**Comment by nchiapol** [comment]
should be fixed (untested)
