### ISSUE TITLE
Export "Excel Haushaltsliste" auf Anlässen fasst Haushalte nicht zusammen

### ISSUE THREAD

**Issue by MrTinnysis** [cevi/hitobito_cevi#51]
Beim Excel Export "Haushaltsliste" auf einem Anlass werden die Personen im selben Haushalt nicht so zusammen gefasst wie dies der gleiche Export auf einer Gruppe macht. Es scheint ein anderer Export auszulösen, der Report sieht gleich aus wie der Export "Alle Angaben".
Kann auch in der Integrationsumgebung reproduziert werden.

**Comment by smathys** [comment]
see https://github.com/hitobito/hitobito/issues/494

**Comment by nchiapol** [comment]
seems fixed
