### ISSUE TITLE
Firmenname bei Haushaltslisten ergänzen

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#56]
Wird eine Haushaltsliste (CSV oder XLS, Abo oder Personenliste) exportiert, so enthält diese nur die Spalten `Name | Adresse | PLZ | Ort | Land | Hauptebene`. Bei Firmen-Kontakten (bei denen wir keinen Vor- oder Namen eingetragen haben) ist die Namensspalte leer. Damit ist der Haushaltsexport mindestens für den wichtigen Use-Case "Spender" nicht brauchbar. 

Mögliche Lösungsoptionen:
  * Spalte "Frimenname"  als neue Spalte exportieren
  * Name im Export zusammensetzen aus Firmenname + bisherigem String (Analog zu Etiketten)
  * Bei Kontakten bei denen nur der Firmenname (aber kein Vor- oder Nachname) definiert ist, im Export den Firmennamen verwenden.

**Comment by maede97** [comment]
Gleiches auch beim Adress-Etiketten-Export

**Comment by nchiapol** [comment]
Adress-Export ist unterdessen korrekt. Rest scheint ungelöst.

**Comment by nchiapol** [comment]
Test-Case in der Integration: https://cevi.puzzle.ch/groups/439/people (Test-Firma)
