### ISSUE TITLE
Haushalt leer gibt Fehler im Log

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#59]
![grafik](https://user-images.githubusercontent.com/14098502/42557184-1520c3c2-84ee-11e8-85bd-2e4f2ba169c4.png)
Falls eine Person nicht in einem Haushalt ist (was bei den meisten der Fall ist), und die Person bearbeitet wird (es muss nicht mal etwas geändert werden), taucht im Log ein Eintrag auf. (siehe Bild)

**Comment by nchiapol** [comment]
seems fixed
