### ISSUE TITLE
Checkbox für AGB und Datenschutzerklärung

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#60]
Gerne möchte der Cevi Schweiz bei seinen Kursen und Anlässen 2 Feldchen einbauen, die man obligatorisch ankreuzen muss:
Und zwar:
  * AGBs
  * Datenschutzerklärung

Mit der Lösung vom RV sind wir nicht so glücklich:
Jeweils ein obligatorisches Fragefeld einfügen und auf die Homepage verweisen.
Wir hätten lieber ein Feldchen, welches automatisch erscheinen würde...wie "bezahlt".

**Comment by nchiapol** [comment]
Meine Meinung: Das braucht es nicht, die Lösung mit Fragefeld ist viel flexibler und mit Hilfe von "Duplizieren" kann das effizient gelöst werden. (habe das deshalb entsprechend getagged.)

_Noch ein Tipp zur Effizienzsteigerung/zum Vermeiden von Fehlern: Ihr könnt bestehende Kurse duplizieren. Dann werden die meisten Einstellungen und alle Fragefelder übernommen. Es macht also wohl Sinn eine Vorlage anzulegen und diese dann jeweils zu kopieren, wenn ihr einen neuen Kurs macht (und der nicht aus dem Vorjahr übernommen werden kann). 
Da der Kurs auch im Status "erstellt" für alle sichtbar ist, muss einfach das Datum so gewählt werden, dass der Vorlagekurs nicht verwirrt (also zum Beispiel mit Start und Ende im 2000 :-)_

**Comment by btemperli** [comment]
@nchiapol braucht es hier noch eine Ergänzung in der Dokumentation? Sonst das Ticket bitte schliessen.
