### ISSUE TITLE
Wiki API Dokumentation aktualisieren

### ISSUE THREAD

**Issue by smathys** [cevi/hitobito_cevi#61]
- [ ] Service API Tokens
- [x] Events

**Comment by maede97** [comment]
wird ergänzt, wenn #76 gefixt wird

**Comment by maede97** [comment]
Teil Events gemacht:
https://wiki.cevi.ch/index.php/CeviDB_API#Endpunkte
https://wiki.cevi.ch/index.php/CeviDB_Release_Notes#API_Schnittstelle_f.C3.BCr_Events

**Comment by nchiapol** [comment]
neues Ticket #109
