### ISSUE TITLE
Hinweis beim Download bezüglich sensibler Daten anzeigen

### ISSUE THREAD

**Issue by smathys** [cevi/hitobito_cevi#62]
Vorschlag von Knox, Email vom 16. Dezember
Beim generieren von Exports aller Art, soll dem Benutzer ein Hinweis angezeigt werden, dass es sich hier um teilweise sensible Daten handelt, und dass er damit vertrauenswürdig umgehen soll.

Frage zur Umsetzung, wir kriegen wir es hin eine Balance zu schaffen, zwischen, nervender Hinweis der jedes Mal erscheint?weggeklickt werden muss, und Sensibilisierung der Leute zum Thema Datenschutz.

**Comment by nchiapol** [comment]
wird durch DSE Anpassungen angegangen (ohne nervigen Hinweis)
