### ISSUE TITLE
Mehrfachmanipulation -> Anlass zuweisen

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#63]
Auf der Produktivumgebung sind ja neuerdings mehrfachmanipulationen aktiv.
Der Button "zu Veranstaltung hinzufügen" macht aber gar nichts.

**Comment by maede97** [comment]
Getestet:
Geht nur Abwärts, das heisst Anlässe von Untergruppen können gefunden werden (sehr langsam!), das andere geht nicht (zuweisen auf höheren Ebenen)

**Comment by nchiapol** [comment]
unklar wie relevant. 
Ugly Workaround: Personen mit Mehrfachmanipulation Tag zuweisen, dann auf hoher Ebene nach diesem Tag suchen und Personen einem Anlass zuweisen; anschliessend Tag wieder entfernen.
