### ISSUE TITLE
Anlässe mit An- und Abmeldung

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#67]
Unsere Sektionsleiter würden gerne die Anmeldung für die Sektionstreffen via CeviDB organisieren. Allerdings sollten sich die ALs auch abmelden, falls sie nicht ans ST kommen. Nötig wäre also mindestens, dass man sich für den Anlass nicht nur an, sondern auch direkt abmelden kann. 

Weitere Interessante Features in diesem Zusammenhang:
  * Liste mit eingeladenen TN hinterlegen (wählbar ob sich auch andere anmelden können oder nicht)
  * Abmeldung für Ortsgruppe und nicht nur für Einzelperson
  * evtl. ganz neuer Anlasstyp, bei dem sich nicht Personen sondern Organisationseinheiten an-/abmelden

**Comment by btemperli** [comment]
Ich glaube fürs Erste würde es reichen, einfach eine "Abmelde-Funktion" zu haben.

**Comment by kronn** [comment]
Aktuell ist es bereits möglich, dass man Teilnehmern erlaubt, sich selbst wieder abzumelden.

Dies kann im Anlass (und auch im Kurs) direkt eingestellt werden:
![anlass-mit-abmeldung](https://user-images.githubusercontent.com/72198/101771447-3b80ff00-3aea-11eb-8aae-909453547f08.png)

Das sieht dann für den Teilnehmer so aus:
![selbst-von-anlass-anmelden](https://user-images.githubusercontent.com/72198/101771379-21472100-3aea-11eb-9fed-9731132808f9.png)

Auch Teilnehmer, die sich nicht selbst angemeldet haben, sondern von Veranstalter als Teilnehmer hinzugefügt wurden, können sind dann selbst anmelden.

Man kann das sicherlich noch anpassen oder erweitern.

Anmeldungen nicht als Person sondern als Gruppe sind mit einer Menge Fragen und Aufwand verbunden. Dies sollte man nochmal extra klären, damit es wirklich ein nützliches Feature wird.

**Comment by btemperli** [comment]
Danke für die Rückmeldung!

Wenn ich die aktuelle Abmelde-Funktion richtig verstehe, werden einfach meine Daten wieder aus der Teilnehmer-Liste gestrichen, sobald ich mich vom Anlass wieder abmelde.

Für gewisse Anlässe wäre es aber nützlich, wenn ich mich nicht nur an- sondern auch abmelden kann, sprich der Organisator sieht in der Teilnehmerliste, wer teilnimmt und wer eben nicht teilnehmen wird. Als Teilnehmer kann ich so aktiv und einfach mitteilen, dass ich am Anlass nicht dabei sein werde.

Die Idee mit der Ortsgruppenanmeldung verstehe ich so, dass wir die Ortsgruppenleiter einladen und sich diese dann nicht als Person anmelden, sondern als Ortsgruppenvertreter. Oder bei einer Delegiertenversammlung melde ich mich dann zwar als Teilnehmer an, aber gebe auch gleich preis, für welche Ortsgruppe/Verband/Region ich mich als Delegierter anmelde. Aber da weiss vielleicht @nchiapol noch weitere Use-Cases dazu. Meiner Meinung nach ist die Idee nicht, dass ich mehrere Personen gleichzeitig anmelde.

**Comment by nchiapol** [comment]
Ich habe selbst eben versucht in https://github.com/hitobito/hitobito_cevi/issues/53 unseren Use-Case besser zu beschreiben. 

Die bestehende Abmelde-Funktion bählt die Info zwar (@btemperli unter Teilnehmende > Abwesende), ist aber für unseren Use-Case schlecht, da dafür ein Umweg über die Anmeldung nötig ist. 

Zu den anderen Punkten:
  * Liste mit eingeladenen TN hinterlegen:
Das Hinzufügen via ist via Personen-Suche sinnvoll möglich. Wir möchten allerdings in diesem Fall eine aktive Bestätigung der Teilnehmer. d.h. wir bräuchten drei Stati: eingeladen, angemeldet und abgemeldet. Im Moment fehlt da der Zustand "Eingeladen"
  * Abmeldung für Ortsgruppe und nicht nur für Einzelperson / Anlasstyp für Organisationseinheiten:
@btemperli's Use-Case entspricht unseren überlegungen. Es ginge darum, Anlässe abzubilden, bei denen Personen als Vertreter einer Gruppe Teilnehmen. Ich denke das könnte mit den Anmelde-Fragen weitgehend abgedeckt werden. Ideal wäre dafür natürlich, wenn man gewisse Fragen auch bei der direkten Abmeldung stellen könnte [1]. Alles weitere geht für den aktuellen Sprint sicher zu weit.

[1] Also dass ich zum Beispiel bei der Anmeldung Fragen zu der Organisationseinheit, meiner Gesundheit und meinem Essenswunsch beantworten muss und falls ich mich direkt Abmelde trotzdem nach der Organisationseinheit gefragt werde.
