### ISSUE TITLE
Mehrfachmanipulation - Auswahl aller Personen einer Gruppe [Rechnung erstellen]

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#68]
Möchte man für eine Gruppe mit mehr als 50 Personen, somit mehr als eine Seite, eine Rechnung erstellen, kann dies nicht auf einmal gemacht werden.

- Wählt man keine Personen an -> '+ Rechnung erstellen' wird eine Rechnung für 50 Personen (Personen der ersten Seite) erstellt.

- Wählt man alle Personen an -> '+ Rechnung erstellen' wird wiederum ein Rechnung nur für 50 Personen erstellt.

- Wählt man mehrer oder alle Personen auf der ersten Seite an, navigiert auf die zweite Seite, geht die Auswahl der ersten Seite verloren.

Somit ist es auf keinem Weg möglich, eine Rechnung für Gruppen mit mehr als 50 Personen auf einmal zu erstellen.

Dasselbe gilt natürlich auch, wenn man allen Personen auf einmal eine neue Rolle zuteilen oder eine bestehende Rolle löschen möchte. 

Zudem kann man nicht einzelne Personen auf verschieden Gruppenseiten auswählen, da die Auswahl beim navigieren der Seiten "verloren" geht.

**Comment by nchiapol** [comment]
Punkte 1 + 2 sind gefixt
