### ISSUE TITLE
Rechnungsartikel - Übersicht Rechnung und Export CSV

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#69]
Werden Rechnungen mit Rechnungsartikel erstellt, wäre es hilfreich, wenn diese bei der Rechnungsübersicht dargestellt werden.

Zudem wären bei einem CSV-Export die Spalten 'Konto' sowie 'Kostenstelle' wünschenswert.

**Comment by nchiapol** [comment]
fixed with 1.20
