### ISSUE TITLE
Finanzrechte für Administrator der Ortsgruppen

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#72]
Popcorn hat gewünscht, dass er als Administrator seiner Ortsgruppe ebenfalls Zugriff auf die Finanzen hat, damit er dort Support leisten kann.

Das tönt nachvollziehbar, die Implikationen müssten aber sicher diskutiert werden.

**Comment by tschuepbach** [comment]
Ist nachvollziehbar.

Wir haben bei unserer Abteilung einfach die Rolle "Kassier", auf der Ebene Ortsgruppe, an folgende Personen vergeben:
- Kassier vom Verein
- Abteilungsleiter
- Vereinspräsident

Somit haben alle wichtigen Personen Zugriff auf das Rechnungsmodul.

**Comment by nchiapol** [comment]
Alles klar. Das ist natürlich nicht im Sinne der DB. Wenn diese Personen auch Zugriff aufs Rechnungsmodul brauchen, sollten wäre es wohl sinnvoll auch ALs und Präsidenten die "Finanz-Rechte" zu geben.

**Comment by nchiapol** [comment]
Lösungsvorschlag Betriebskommission: Rolle Kassier auch an weitere Personen vergeben, aber Bezeichnung vermerken.
