### ISSUE TITLE
Bezeichnung bei Listenimport

### ISSUE THREAD

**Issue by tschuepbach** [cevi/hitobito_cevi#74]
Beim Import von CSV-Listen wäre es praktisch, wenn zusätzlich zur Rolle auch die Bezeichnung für die importierten Rollen vergeben werden könnte.

![unbenannt](https://user-images.githubusercontent.com/40494600/52467962-7f6dea80-2b87-11e9-93bb-4beeee384c51.png)

Auf der Regionsebene haben wir Gruppen, z. B. Spender, wo jede Person über eine Bezeichnung innerhalb der Gruppe verfügt.

Aktuell müssen alle Personen nach dem Import einzeln angepasst werden. Die Bezeichnung kann leider nicht über die Mehrfachaktionen geändert werden.

**Comment by nchiapol** [comment]
Setzen wir nur um, falls das eine neue MIO nutzen und finanzieren möchte.

**Comment by nchiapol** [comment]
zu alt, wir schliessen das; neues Issue kann eröffnet werden, falls Ostschweiz das möchte.
