### ISSUE TITLE
Service-Token-API: fehlende Angaben

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#76]
Fehlend (u.a.)
* Geschlecht
* Geburtsdatum
Es werden nur Daten angezeigt, welche im grauen Kasten auf der Seite angezeigt werden ( und komischerweise aber auch z.B. Name der Eltern)

Diese fehlenden Daten werden aber genau z.B. beim automatischen erstellen einer Adressliste genutzt.

**Comment by MrTinnysis** [comment]
https://github.com/hitobito/hitobito/issues/586

**Comment by MrTinnysis** [comment]
Gemäss Hitobito eine generelle Einstellung die für den Wagon angepasst werden kann.

**Comment by MrTinnysis** [comment]
https://github.com/hitobito/hitobito_pbs/issues/117

**Comment by nchiapol** [comment]
Hatte heute eine Anfrage aus einer Ortsgruppe, sie haben ebenfalls die Mail-Adressen vermisst.

**Comment by maede97** [comment]
Siehe hitobito/hitobito#1460

**Comment by maede97** [comment]
Scheinbar jetzt implementiert?
Muss getestet werden.

**Comment by nchiapol** [comment]
Habe das eben kontrolliert: wenn ich mich via Service-Token zugreife sehe ich jetzt Geburtsdatum, Geschlecht und alle Mailadressen. Der Kurs Endpunkt scheint unverändert (https://github.com/cevi/hitobito_cevi/issues/154)
