### ISSUE TITLE
Export für BSV

### ISSUE THREAD

**Issue by MrTinnysis** [cevi/hitobito_cevi#78]
Für einen BSV passenden Export wären folgenden Daten nötig:
-	Nachname
-	Vorname
-	Adresse (Strasse, Nr, PLZ Wohnort)
-	Wohnkanton
-	Jahrgang

(aus Mail von Kiebitz)

**Comment by maede97** [comment]
Ist das nicht mit hitobito/hitobito#115 auch machbar und braucht nichts zusätzliches?

**Comment by btemperli** [comment]
Ein weiterer Wunsch ist hinzugekommen:
Ein Export der nötigen Zahlen direkt ins [BSV-Formular](https://www.cevi.ch/bsv/?file=files/cevi/pdf/BSV/Neu/BSV_Kursabschluss_Formular_def_2019.docx).

Ich glaube allerdings, dass der Import in ein .docx-file ziemlich komplex ist und es wohl einfacher ist, mit einem normalen "BSV-Export" die richtigen Werte zu erhalten und diese dann von Hand zu übertragen. Ich bin auch nicht sicher, wie oft sich dieses .docx ändert...

@maede97 ich bin mir nicht sicher, ob das Problem mit https://github.com/hitobito/hitobito/issues/115 behoben wird. Da muss der Kursleiter ja dann auch zuerst die richtigen Spalten auswählen und ist wieder unnötig lange damit beschäftigt.

Ich nehme an, wir könnten hier eventuell mit der Lösung von der PBS arbeiten oder diese zumindest mal überprüfen: https://github.com/hitobito/hitobito/issues/670

**Comment by nchiapol** [comment]
Ich sehe zwei Optionen:
  * wir können mit wenig Aufwand die Lösung(en) der Pfadi übernehmen. Dafür müssten wir aber zuerst noch wissen, was die Lösungen überhaupt können.
  * Wir implementieren einfach einen Zusätzlichen Export bei Anlässen+Kurse mit den Spalten gemäss erstem Post

**Comment by nchiapol** [comment]
BSV Export gibt es auf https://db.cevi.ch/list_courses (mindestens für Admins auf Stufe CCH) mit der Statistik alle Kurse in der DB.

Weiteres Vorgehen: Export und BSV-Abrechnungsprozess mit GS CCH besprechen.

**Comment by nchiapol** [comment]
läuft in anderen Tickets
