### ISSUE TITLE
SportDB Export bei Lager: NDBJS_PERS_NR leer

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#79]
Die Spalte NDBJS_PERS_NR sollte ja eigentlich die J+S-Leiter-Nummer beinhalten. Im Export mit CSV (SportDB oder NDBJS) ist die Spalte aber immer komplett leer.

**Comment by nchiapol** [comment]
In Mail an Andre angesprochen

**Comment by nchiapol** [comment]
https://github.com/hitobito/hitobito/issues/775

**Comment by btemperli** [comment]
Wird gemäss Mail von André heute Nachmittag (12. juni) deployed.

**Comment by maede97** [comment]
Gefixt
