### ISSUE TITLE
Neue Mitgliedsorganisation: Outdoortech

### ISSUE THREAD

**Issue by btemperli** [cevi/hitobito_cevi#80]
Outdoortech als neue Mitgliedsorganisation aufnehmen.

**Comment by btemperli** [comment]
Mitgliedsorganisation ist aufgesetzt. Noch nicht wirklich in Verwendung.

**Comment by nchiapol** [comment]
nichts passiert - weder in DB noch im Hinblick auf Umwandlung zu MIO

**Comment by nchiapol** [comment]
hat sich erübrigt - wird nicht als MIO genutzt und wurde gelöscht
