### ISSUE TITLE
Info-Page Status

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#87]
Kann Hitobito eine Info-Page irgendwo hosten:
* Welche Instanz läuft auf Produktiv?
* Welche Instanz läuft auf der Test-Instanz?

Beides evtl. mit aktuellem Git-Commit

Früher wurde im Footer noch die Build-Version angezeigt, dies ist jetzt nicht mehr da.

**Comment by nchiapol** [comment]
In Mail an Andre angesprochen

**Comment by maede97** [comment]
Update: In der Test-Umgebung wird nun (aktuell) 1.19.8 angezeigt. Ich glaube, vorher war nur 1.19, da scheint sich also etwas getan zu haben.

**Comment by maede97** [comment]
Wurde mit dem Update auf 1.20 erledigt.
