### ISSUE TITLE
TN-Angaben für Events (u.A. AHV)

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#91]
![image](https://user-images.githubusercontent.com/14098502/60087574-916ab700-973d-11e9-86ea-933ae72f3039.png)

Viele Angaben sind nicht bei den TN/Leitern erfasst, und werden aber für J+S gebraucht.

-- Mail Chinchilla vom  20. Juni 19

**Comment by maede97** [comment]
Was ich mich frage:
Müssten dann nicht ALLE Personen, welche an einem J+S-Lager teilnehmen, die AHV-Nummer erfassen? Ich glaube nicht, dass das per sofort übernommen werden kann? Sonst müssten ja alle Abteilungen noch informiert werden?

**Comment by maede97** [comment]
Laut [Merkblatt](https://www.jugendundsport.ch/content/jus-internet/de/infos-fuer/j-s-coaches/sportdb--hinweise-hilfe-/angebot-anmelden/_jcr_content/contentPar/accordion_copy/accordionItems/merkbl_tter_zum_teil/accordionPar/downloadlist/downloadItems/47_1456398355913.download/3_Anforderungen_SPORTdb_d.pdf) J+S zum Import in die SportDB ist die AHV-Nummer nur "wünschenswert"

**Comment by nchiapol** [comment]
scheint korrigiert (funktioniert auf integration)
