### ISSUE TITLE
CeviDB-Mailer: Falscher Link im Footer

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#92]
Im Footer eines Mails via CeviDB-Mailingliste steht ja:

Info zur Gruppe https://www.cevi.ch/gruppe/cevidb
Der Link existiert nicht.

**Comment by btemperli** [comment]
@maede97 weisst du was auf der Seite angezeigt wurde oder was angezeigt werden soll? Ich gehe stark davon aus, dass die Seite mit der neuen Cevi-Webseite verschwunden ist.

**Comment by maede97** [comment]
Nein leider nicht mehr. Vielleicht weiss es @nchiapol aber?

**Comment by btemperli** [comment]
Ich bin gerade nicht sicher, ob das überhaupt ein Problem von der Datenbank ist oder ein Problem von den Cevi-Maillist's. Der Link wird ja via Maillist im Email eingefügt, das Mail kommt ja nicht von einem Abo aus der Datenbank sondern von einer allgemeinen Maillist vom Cevi Schweiz.

**Comment by nchiapol** [comment]
Das ist definitiv ein allgemeines Problem der Cevi-Maillists. Der falsche Link ist auch in den Mail an die präsidenten-Liste enthalten.
