### ISSUE TITLE
Run Hitobito Cevi Wagon in Docker

### ISSUE THREAD

**Issue by btemperli** [cevi/hitobito_cevi#93]
Anleitung gemäss https://github.com/nxt-engineering/hitobito-docker

Weitere Issues / Pull Requests zum Thema bei Hitobito:
https://github.com/hitobito/hitobito/pull/774

Folgende Wagons habe ich bei mir geklont:
https://github.com/hitobito/hitobito
https://github.com/hitobito/hitobito_youth
https://github.com/hitobito/hitobito_cevi

Die Login-Seite läuft unter https://localhost:32769. Fürs erste sieht's soweit gut aus, aber es gibt noch ein paar Probleme.

Mac OS X, Docker Desktop for Mac (siehe https://docs.docker.com/docker-for-mac/install/)

**Comment by btemperli** [comment]
Nach dem Login tauch im Moment ein Fehler: "NoMethodError in DashboardController#index" auf.

**Comment by btemperli** [comment]
ähnliche Probleme auch bei hitobito selber. Evtl Datenbankproblem. Siehe: https://github.com/hitobito/hitobito/issues/844

**Comment by btemperli** [comment]
Mit den Anpassungen von carlo (https://github.com/carlobeltrame/hitobito-docker/tree/fix-wagon-setup) läufts bei mir.

**Comment by maede97** [comment]
https://github.com/hitobito/development scheint da vielversprechend.

**Comment by maede97** [comment]
Das neue Setup mit dem Dev-Repo funktioniert bei mir (Ubuntu 20.04 LTS). Ich denke, dies können wir schliessen?

**Comment by nchiapol** [comment]
Dev-Setup funktioniert auch bei mir gut
