### ISSUE TITLE
QR Code Rechnungen

### ISSUE THREAD

**Issue by MrTinnysis** [cevi/hitobito_cevi#97]
Ab dem 30. Juni 2020 kann auf den neuen Einzahlungsschein nach Standard ISO 20022 umgestellt werden. Dies wäre wohl etwas für den nächsten grossen Hitobitorelease Herbst im 2020...

**Comment by MrTinnysis** [comment]
https://github.com/hitobito/hitobito/issues/589

**Comment by nchiapol** [comment]
scheint auf der Integration umgesetzt
