### ISSUE TITLE
API Service Tokens haben keinen Zugriff auf die Spender

### ISSUE THREAD

**Issue by MrTinnysis** [cevi/hitobito_cevi#98]
Durch eine der beiden Änderungen https://github.com/cevi/hitobito_cevi/issues/12, https://github.com/hitobito/hitobito_cevi/issues/39 wurde auch der Zugriff der API Service Tokens auf die Spender gekillt. Ich denke dies ist nicht ausschliesslich schlecht, sollte aber mit einem zusätzlichen Recht bei Bedarf aktiviert werden können. Da beispielsweise das Finanztool der Region Bern vorzugsweise mit einem Service Token laufen würde. Habe dies temporär im Finanztool umgestellt und vorerst noch nicht weitergeleitet.
Wie sind eure Meinungen dazu?

**Comment by MrTinnysis** [comment]
Ich wäre für eine neue Berechtigung:
**Spender dieser Ebene**
ohne Zugriff auf Spender darunterliegender Ebenen.

**Comment by MrTinnysis** [comment]
Anpassen zusammen mit den generellen Berechtigungen der API Tokens: #76

Entweder als neue Berechtigung für Tokens oder generelle Freischaltung für alle Tokens.

**Comment by MrTinnysis** [comment]
Ich habe noch einen Bug im Bereich Spenderrolle - API Service Token gefunden und dokumentiert: https://github.com/hitobito/hitobito_cevi/issues/78

**Comment by nchiapol** [comment]
umgesetzt mit Sprint 2022
