### ISSUE TITLE
Anzahl TN auf Event-Seite wird nicht korrekt aktualisiert

### ISSUE THREAD

**Issue by maede97** [cevi/hitobito_cevi#99]
Bei einer Event-Übersicht zeigt in der rechten Spalte die Übersicht eine falsche Zahl an:

1. Person als Leiter bei einem neuen Event hinzufügen (Übersicht zeigt "Anmeldungen: 0 Anmeldungen")
2. Personen als TN hinzufügen (Übersicht zeigt "X Anmeldungen")
3. Eine Person von TN zu Leiter wechseln (Übersicht zeigt immer noch "X Anmeldungen" anstelle X-1)
4. Eine neue Person hinzufügen als TN (Übersicht wird wieder korrigiert.)

Aufgefallen in Produktion und auch "erfolgreich" getestet in Integration.

**Comment by maede97** [comment]
Der Bug tritt nicht auf, wenn eine Person gelöscht wird.

**Comment by maede97** [comment]
Hängt evtl mit https://github.com/hitobito/hitobito/issues/971 zusammen?

**Comment by nchiapol** [comment]
gefixt auf der Integration
